import { createActions } from 'redux-actions';

const {
  getListingDetail,
  getListingDetailSucceeded,
  getListingDetailFailed,
  setActiveCurrency,
  getMyListings,
  setBitcoinPrice,
  setOmnicoinPrice,
  setContinuous,
  addListingImage,
  deleteListingImage,
  startDeleteListingImage,
  deleteListingImageSuccess,
  deleteListingImageError,
  setListingImages,
  uploadListingImage,
  uploadListingImageSuccess,
  uploadListingImageError,
  clearListingImageError,
  resetSaveListing,
  saveListing,
  saveListingSuccess,
  saveListingError,
  resetDeleteListing,
  deleteListing,
  deleteListingSuccess,
  deleteListingError,
  isFavorite,
  addToFavorites,
  removeFromFavorites,
  getFavorites
} = createActions({
  GET_LISTING_DETAIL: (listingId) => ({ listingId }),
  GET_LISTING_DETAIL_SUCCEEDED: (listingDetail) => ({ listingDetail }),
  GET_LISTING_DETAIL_FAILED: (error) => ({ error }),
  SET_ACTIVE_CURRENCY: (activeCurrency) => ({ activeCurrency }),
  GET_MY_LISTINGS: (myListings) => ({ myListings }),
  SET_BITCOIN_PRICE: () => ({}),
  SET_OMNICOIN_PRICE: () => ({}),
  SET_CONTINUOUS: () => ({}),
  ADD_LISTING_IMAGE: (file, imageId) => ({ file, imageId }),
  DELETE_LISTING_IMAGE: (image) => ({ image }),
  START_DELETE_LISTING_IMAGE: (imageId) => ({ imageId }),
  DELETE_LISTING_IMAGE_SUCCESS: (imageId) => ({ imageId }),
  DELETE_LISTING_IMAGE_ERROR: (imageId, error) => ({ imageId, error }),
  SET_LISTING_IMAGES: (images) => ({ images }),
  UPLOAD_LISTING_IMAGE: (file, imageId) => ({ file, imageId }),
  UPLOAD_LISTING_IMAGE_SUCCESS: (imageId, image, thumb, fileName) => ({
    imageId,
    image,
    thumb,
    fileName
  }),
  UPLOAD_LISTING_IMAGE_ERROR: (imageId, error) => ({ imageId, error }),
  CLEAR_LISTING_IMAGE_ERROR: (imageId) => ({ imageId }),
  RESET_SAVE_LISTING: () => ({}),
  SAVE_LISTING: (listing, listingId) => ({ listing, listingId }),
  SAVE_LISTING_SUCCESS: (listing, listingId) => ({ listing, listingId }),
  SAVE_LISTING_ERROR: (listingId, error) => ({ listingId, error }),
  RESET_DELETE_LISTING: () => ({}),
  DELETE_LISTING: (listingId) => ({ listingId }),
  DELETE_LISTING_SUCCESS: (listingId) => ({ listingId }),
  DELETE_LISTING_ERROR: (listingId, error) => ({ listingId, error }),
  IS_FAVORITE: (listingDetailId) => ({ listingDetailId }),
  ADD_TO_FAVORITES: (listingDetail) => ({ listingDetail }),
  REMOVE_FROM_FAVORITES: (listingDetailId) => ({ listingDetailId }),
  GET_FAVORITES: () => ({}),
});

export {
  getListingDetail,
  getListingDetailSucceeded,
  getListingDetailFailed,
  setActiveCurrency,
  getMyListings,
  setBitcoinPrice,
  setOmnicoinPrice,
  setContinuous,
  addListingImage,
  deleteListingImage,
  startDeleteListingImage,
  deleteListingImageSuccess,
  deleteListingImageError,
  setListingImages,
  uploadListingImage,
  uploadListingImageSuccess,
  uploadListingImageError,
  clearListingImageError,
  resetSaveListing,
  saveListing,
  saveListingSuccess,
  saveListingError,
  resetDeleteListing,
  deleteListing,
  deleteListingSuccess,
  deleteListingError,
  isFavorite,
  addToFavorites,
  removeFromFavorites,
  getFavorites
};
