import { createActions } from 'redux-actions';

const {
  getListingDetail,
  setActiveCurrency,
  getMyListings,
  setBitcoinPrice,
  setOmnicoinPrice,
  setContinuous,
  addListingImage,
  deleteListingImage,
  startDeleteListingImage,
  deleteListingImageSuccess,
  deleteListingImageError,
  setListingImages,
  uploadListingImage,
  uploadListingImageSuccess,
  uploadListingImageError,
  clearListingImageError,
  isFavorite,
  addToFavorites,
  removeFromFavorites,
  getFavorites
} = createActions({
  GET_LISTING_DETAIL: (listingDetail) => ({ listingDetail }),
  SET_ACTIVE_CURRENCY: (activeCurrency) => ({ activeCurrency }),
  GET_MY_LISTINGS: (myListings) => ({ myListings }),
  SET_BITCOIN_PRICE: () => ({}),
  SET_OMNICOIN_PRICE: () => ({}),
  SET_CONTINUOUS: () => ({}),
  ADD_LISTING_IMAGE: (file, imageId) => ({ file, imageId }),
  DELETE_LISTING_IMAGE: (image) => ({ image }),
  START_DELETE_LISTING_IMAGE: (imageId) => ({ imageId }),
  DELETE_LISTING_IMAGE_SUCCESS: (imageId) => ({ imageId }),
  DELETE_LISTING_IMAGE_ERROR: (imageId, error) => ({ imageId, error }),
  SET_LISTING_IMAGES: (images) => ({ images }),
  UPLOAD_LISTING_IMAGE: (file, imageId) => ({ file, imageId }),
  UPLOAD_LISTING_IMAGE_SUCCESS: (imageId, image, thumb, fileName) => ({
    imageId,
    image,
    thumb,
    fileName
  }),
  UPLOAD_LISTING_IMAGE_ERROR: (imageId, error) => ({ imageId, error }),
  CLEAR_LISTING_IMAGE_ERROR: (imageId) => ({ imageId }),
  IS_FAVORITE: (listingDetailId) => ({ listingDetailId }),
  ADD_TO_FAVORITES: (listingDetail) => ({ listingDetail }),
  REMOVE_FROM_FAVORITES: (listingDetailId) => ({ listingDetailId }),
  GET_FAVORITES: () => ({}),
});

export {
  getListingDetail,
  setActiveCurrency,
  getMyListings,
  setBitcoinPrice,
  setOmnicoinPrice,
  setContinuous,
  addListingImage,
  deleteListingImage,
  startDeleteListingImage,
  deleteListingImageSuccess,
  deleteListingImageError,
  setListingImages,
  uploadListingImage,
  uploadListingImageSuccess,
  uploadListingImageError,
  clearListingImageError,
  isFavorite,
  addToFavorites,
  removeFromFavorites,
  getFavorites
};
