#!/bin/sh
if ! [ -d "$HOME/Library/Application Support/OmniBazaar" ]; then
mkdir "$HOME/Library/Application Support/OmniBazaar";
fi

echo "$2/Contents/MacOS/ob2"

cp -f "$2/Contents/MacOS/ob2" "$HOME/Library/Application Support/OmniBazaar/."
chown -R $USER "$HOME/Library/Application Support/OmniBazaar"

name=$(basename "$1")

mkdir "$HOME/Library/Preferences/OmniBazaar"
chown -R $USER "$HOME/Library/Preferences/OmniBazaar"
rm "$HOME/Library/Preferences/OmniBazaar/omnibazaar.set"
echo "referrer=$name" >> "$HOME/Library/Preferences/OmniBazaar/omnibazaar.set"

exit 0
