#!/bin/sh
# expand template variables + preserve formatting
render_template() {
  eval "echo \"$(cat $1)\""
}

if ! [ -d "$HOME/Library/Application Support/OmniBazaar" ]; then
    mkdir "$HOME/Library/Application Support/OmniBazaar";
fi

echo "$2/Contents/MacOS/ob2"
cp -f "$2/Contents/MacOS/ob2" "$HOME/Library/Application Support/OmniBazaar/."

# check is node is running
node_running=0
if pgrep -x "witness_node" > /dev/null
then
    killall witness_node
    node_running=1
fi

if [ ! -f "$HOME/Library/Application Support/OmniBazaar/witness_node/witness_node" ]; then
    unzip -o "$2/Contents/MacOS/witness_node.zip" -d "$HOME/Library/Application Support/OmniBazaar"
else
    unzip -o "$2/Contents/MacOS/witness_node.zip" -d "$2/Contents/MacOS"
    cp -f "$2/Contents/MacOS/witness_node/witness_node" "$HOME/Library/Application Support/OmniBazaar/witness_node"
    rm -rf "$2/Contents/MacOS/witness_node"
fi

chown -R $USER "$HOME/Library/Application Support/OmniBazaar"

name=$(basename "$1")

mkdir "$HOME/Library/Preferences/OmniBazaar"
chown -R $USER "$HOME/Library/Preferences/OmniBazaar"
rm "$HOME/Library/Preferences/OmniBazaar/omnibazaar.set"
echo "referrer=$name" >> "$HOME/Library/Preferences/OmniBazaar/omnibazaar.set"

render_template service/omnibazaar.witness_node.plist >/Library/LaunchAgents/omnibazaar.witness_node.plist

# restart the node
if [ "$node_running" -eq 1 ];
then
    sleep 5
    "$HOME/Library/Application Support/OmniBazaar/witness_node/"witness_node </dev/null &>/dev/null &
fi

exit 0
