#!/bin/sh
# expand template variables + preserve formatting
render_template() {
  eval "echo \"$(cat $1)\""
}

if ! [ -d "$HOME/Library/Application Support/OmniBazaar" ]; then
mkdir "$HOME/Library/Application Support/OmniBazaar";
fi

echo "$2/Contents/MacOS/ob2"

cp -f "$2/Contents/MacOS/ob2" "$HOME/Library/Application Support/OmniBazaar/."
unzip -o "$2/Contents/MacOS/witness_node.zip" -d "$HOME/Library/Application Support/OmniBazaar"

chown -R $USER "$HOME/Library/Application Support/OmniBazaar"

name=$(basename "$1")

mkdir "$HOME/Library/Preferences/OmniBazaar"
chown -R $USER "$HOME/Library/Preferences/OmniBazaar"
echo "referrer=$name" >> "$HOME/Library/Preferences/OmniBazaar/omnibazaar.set"

render_template service/omnibazaar.witness_node.plist >/Library/LaunchAgents/omnibazaar.witness_node.plist

exit 0
